language: node_js
before_script:
  - if [ "$TRAVIS_NODE_VERSION" = "0.10" ]; then npm i node-zlib-backport; fi
after_success:
  - if [ "$TRAVIS_NODE_VERSION" = "5" ]; then npm run coverage && npm i coveralls@2 && npm run coveralls; fi
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
